### ISSUE TITLE
Package failing with a long stack

### ISSUE THREAD

**Issue by reflash** [sergioramos/serverless-plugin-tree-shake#173]
Hi! I am using the plugin and after some changes in my project I'm now getting the following:
```shell
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at until (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:15:10)
at engineUntil (/.../node_modules/apr-engine-until/dist/apr-engine-until.umd.js:19:10)
at group (/.../node_modules/apr-engine-iterator/dist/apr-engine-iterator.umd.js:21:12)
at Object.next (/.../node_modules/apr-engine-iterator/dist/apr-engine-iterator.umd.js:28:14)
at next (/.../node_modules/apr-engine-run/dist/apr-engine-run.umd.js:29:22)
at /.../node_modules/apr-engine-run/dist/apr-engine-run.umd.js:42:12
at new Promise (<anonymous>)
at engineRun (/.../node_modules/apr-engine-run/dist/apr-engine-run.umd.js:41:10)
at engineEach (/.../node_modules/apr-engine-each/dist/apr-engine-each.umd.js:11:10)
at run (/.../node_modules/apr-map/dist/apr-map.umd.js:14:10)
at map (/.../node_modules/apr-map/dist/apr-map.umd.js:82:10)
at WriteStream.<anonymous> (/.../node_modules/serverless-plugin-tree-shake/index.js:386:17)
at WriteStream.emit (events.js:314:20)
at WriteStream.EventEmitter.emit (domain.js:483:12)
at /.../node_modules/graceful-fs/graceful-fs.js:325:14
at /.../node_modules/graceful-fs/graceful-fs.js:352:16
at /.../node_modules/graceful-fs/graceful-fs.js:352:16
at FSReqCallback.oncomplete (fs.js:156:23)
```

I'm using a monorepo (yarn workspaces) and the thing I changed is added my workspaces folder in node_modules to serverless.package.includes section.
I suspected that it could be related to circular links or something like that, so I tried to exclude them, but still no success:
```yaml
package:
  excludeDevDependencies: false
  include:
    ...
    - '!node_modules/@project/**/node_modules/**/*.*'
    - 'node_modules/@project/**/*.*'
``` 

Is there anything I could try or check? I'm unable to get a lot of debug info because this output stack takes all of my terminal space

**Comment by reflash** [comment]
I've checked some more details:

```
Serverless: 11003
 
  Range Error --------------------------------------------
 
  RangeError: Maximum call stack size exceeded
```

fails in following code:
```javascript
this.serverless.cli.log(files.length);
const contents = Flatten(
  await Map(
    Uniq(files.map((pathname) => normalize(pathname))),
    (fullpath) => this.getFileContentAndStat(fullpath),
  ),
);
```

**Comment by reflash** [comment]
worked around that for now with:
```bash
npx --node-arg=--stack-size=4096 sls deploy --stage production
```

Seems that there's too many files included into the final package
